name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'

    - name: Install Protoc
      uses: arduino/setup-protoc@v1

    - name: Install dependencies
      run: make deps

    - name: Run greet
      run: make greet

    - name: Run clean
      run: make clean
